import "./globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";

export const Pretendard = localFont({
  src: "../../public/fonts/PretendardVariable.woff2",
});

export const metadata: Metadata = {
  title: "꿋꿋",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={Pretendard.className}>{children}</body>
    </html>
  );
}
